<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56c09a3dcaa1f',
	'title' => 'Flexible Content Blocks',
	'fields' => array (
		array (
			'key' => 'field_56c09a49d16c4',
			'label' => 'Content Area',
			'name' => 'flexible_content_area',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add block',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '564de7fa50fca',
					'name' => 'download',
					'label' => 'Download CTA',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_564deab5d1d62',
							'label' => 'Link Text',
							'name' => 'link_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_564de84f50fcb',
							'label' => 'File',
							'name' => 'file',
							'type' => 'file',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5641c2475349f',
					'name' => 'content_wysiwyg_editor',
					'label' => 'WYSIWYG Editor',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5641c260534a0',
							'label' => 'Body',
							'name' => 'body',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_5641c2dd534a1',
							'label' => 'Add CTA Button?',
							'name' => 'add_cta_button',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_5641c322534a2',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5641c2dd534a1',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'View more',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5641c352534a3',
							'label' => 'Link Location',
							'name' => 'link_location',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5641c2dd534a1',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Internal Link' => 'Internal Link',
								'External Link' => 'External Link',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_5641c396534a4',
							'label' => 'Page Link',
							'name' => 'page_link',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5641c2dd534a1',
										'operator' => '==',
										'value' => '1',
									),
									array (
										'field' => 'field_5641c352534a3',
										'operator' => '==',
										'value' => 'Internal Link',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'allow_archives' => 1,
						),
						array (
							'key' => 'field_5641c3be534a6',
							'label' => 'External Link',
							'name' => 'external_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5641c2dd534a1',
										'operator' => '==',
										'value' => '1',
									),
									array (
										'field' => 'field_5641c352534a3',
										'operator' => '==',
										'value' => 'External Link',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5887428a75a6e',
							'label' => 'Link opens in a new tab',
							'name' => 'content_wysiwyg_editor_links_new_tab',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5641c2dd534a1',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56c1f57d74e95',
					'name' => 'gravity_form',
					'label' => 'Gravity Form',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56c1f58874e96',
							'label' => 'Form',
							'name' => 'form',
							'type' => 'gravity_forms_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'allow_null' => 0,
							'allow_multiple' => 0,
						),
						array (
							'key' => 'field_5885e92588d3d',
							'label' => 'Show Form Title?',
							'name' => 'show_form_title_gravity_form',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_5885e94188d3e',
							'label' => 'Show Form Description?',
							'name' => 'show_form_description_gravity_form',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56bc61e129ca3',
					'name' => 'gallery',
					'label' => 'Gallery',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56bc61fb55871',
							'label' => 'Gallery',
							'name' => 'gallery',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg, jpeg, gapng, gif, bmp',
							'insert' => 'append',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56bcb617e3b74',
					'name' => 'quote',
					'label' => 'Quote',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56bcb6c7d55d3',
							'label' => 'Quote',
							'name' => 'quote',
							'type' => 'textarea',
							'instructions' => 'Enter a quotation.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56bcb6fbd55d4',
							'label' => 'Citation',
							'name' => 'citation',
							'type' => 'text',
							'instructions' => 'Enter the author name.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Enter the author name.',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56bcb717d55d5',
							'label' => 'Avatar',
							'name' => 'avatar',
							'type' => 'image',
							'instructions' => 'Choose and avatar image (should be a perfect square e.g. 126px x 126px).',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56c2e6fc9d472',
					'name' => 'accordion',
					'label' => 'Accordion',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56c2e7059d473',
							'label' => 'Accordion Items',
							'name' => 'accordion_items',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => 'Add Row',
							'sub_fields' => array (
								array (
									'key' => 'field_56c2e72e9d474',
									'label' => 'Accordion item heading',
									'name' => 'accordion_item_heading',
									'type' => 'text',
									'instructions' => 'Enter a heading for this accordion item.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_56c2e74b9d475',
									'label' => 'Accordion item content',
									'name' => 'accordion_item_content',
									'type' => 'wysiwyg',
									'instructions' => 'Enter your content for the accordion item.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
								),
								array (
									'key' => 'field_56c2e7829d476',
									'label' => 'Accordion item link title',
									'name' => 'accordion_item_link_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'Enter a title for a link (optional)',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_577142ac57f8d',
									'label' => 'Add a Link?',
									'name' => 'accordion_item_add_a_link',
									'type' => 'true_false',
									'instructions' => '',
									'required' => '',
									'conditional_logic' => '',
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
								),
								array (
									'key' => 'field_57713e860a14e',
									'label' => 'Link Location',
									'name' => 'accordion_item_link_location',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_577142ac57f8d',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'Internal Link' => 'Internal Link',
										'External Link' => 'External Link',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'vertical',
									'return_format' => 'value',
								),
								array (
									'key' => 'field_57713d800a14d',
									'label' => 'Internal Link',
									'name' => 'accordion_item_internal_link',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_57713e860a14e',
												'operator' => '==',
												'value' => 'Internal Link',
											),
											array (
												'field' => 'field_577142ac57f8d',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'allow_archives' => 1,
								),
								array (
									'key' => 'field_56c2e7989d477',
									'label' => 'External Link',
									'name' => 'accordion_item_external_link',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_57713e860a14e',
												'operator' => '==',
												'value' => 'External Link',
											),
											array (
												'field' => 'field_577142ac57f8d',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array (
									'key' => 'field_588740c375a6b',
									'label' => 'Link opens in a new tab',
									'name' => 'accordion_item_links_new_tab',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_577142ac57f8d',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
								),
							),
						),
						array (
							'key' => 'field_56c2e7b99d478',
							'label' => 'Close open items when one is opened?',
							'name' => 'close_other_items',
							'type' => 'true_false',
							'instructions' => 'When this is set to true, when you open an accordion item, any currently open item will be closed.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56be175e0cec3',
					'name' => 'cta',
					'label' => 'CTA',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56be17672326a',
							'label' => 'CTA text',
							'name' => 'cta_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56be177f2326b',
							'label' => 'CTA link title',
							'name' => 'cta_link_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_57712fb99182f',
							'label' => 'Link Location',
							'name' => 'cta_link_location',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Internal Link' => 'Internal Link',
								'External Link' => 'External Link',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_5771302891830',
							'label' => 'Page Link',
							'name' => 'cta_internal_link',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_57712fb99182f',
										'operator' => '==',
										'value' => 'Internal Link',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'allow_archives' => 1,
							'multiple' => 0,
						),
						array (
							'key' => 'field_56be179b2326c',
							'label' => 'External Link',
							'name' => 'cta_external_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_57712fb99182f',
										'operator' => '==',
										'value' => 'External Link',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5887414875a6c',
							'label' => 'Link opens in a new tab',
							'name' => 'cta_links_new_tab',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56c2ed844488b',
					'name' => 'table-layout',
					'label' => 'Table',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56c2ee5c423c1',
							'label' => 'Table Block',
							'name' => 'table_block',
							'type' => 'table',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'use_header' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56c3320393893',
					'name' => 'image_with_caption',
					'label' => 'Image with caption',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56c3323093894',
							'label' => 'Image',
							'name' => 'image-block-image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_56c336096ae71',
							'label' => 'Caption',
							'name' => 'image-block-caption',
							'type' => 'textarea',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5773ec8ba2298',
					'name' => 'video_with_caption',
					'label' => 'Video with caption',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5773ec99a2299',
							'label' => 'Video',
							'name' => 'video_with_caption_embed',
							'type' => 'oembed',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'width' => '',
							'height' => '',
						),
						array (
							'key' => 'field_5773ed2ca229a',
							'label' => 'Caption',
							'name' => 'video_with_caption_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '57681bbb6ff3f',
					'name' => 'links',
					'label' => 'Links',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_57681bc76ff40',
							'label' => 'Title',
							'name' => 'links_title',
							'type' => 'text',
							'instructions' => 'Enter a title to sit above your block of links.',
							'required' => 1,
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'E.g. Links',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_57681bfb6ff41',
							'label' => 'Links:',
							'name' => 'links_links',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'row',
							'button_label' => 'Add Link',
							'sub_fields' => array (
								array (
									'key' => 'field_57681c2a6ff42',
									'label' => 'Link title',
									'name' => 'links_link_title',
									'type' => 'text',
									'instructions' => 'A title for the link',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'E.g. Contact us',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_57681c4c6ff43',
									'label' => 'Type of link?',
									'name' => 'links_link_type',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'Internal Link' => 'Internal Link',
										'External Link' => 'External Link',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'vertical',
									'return_format' => 'value',
								),
								array (
									'key' => 'field_57681cd36ff44',
									'label' => 'Internal link',
									'name' => 'links_internal_link',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_57681c4c6ff43',
												'operator' => '==',
												'value' => 'Internal Link',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'allow_archives' => 1,
								),
								array (
									'key' => 'field_57681d356ff45',
									'label' => 'External link',
									'name' => 'links_external_link',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_57681c4c6ff43',
												'operator' => '==',
												'value' => 'External Link',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'E.g. http://www.google.co.uk',
								),
								array (
									'key' => 'field_588741fb75a6d',
									'label' => 'Link opens in a new tab',
									'name' => 'links_new_tab',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
								),
								array (
									'key' => 'field_57681d606ff46',
									'label' => 'Link image',
									'name' => 'links_link_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'posts_page',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'front_page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'templates/promotion-page.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'templates/contact.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'templates/page-leader.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'templates/donations-landing.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'templates/donations-process.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'templates/feature-board.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'templates/voting-leader.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'templates/national.php',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'jobs',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'services',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'events',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'briefings',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'candidates',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'pressreleases',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
