<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56c592ee759b6',
	'title' => 'Homepage Header',
	'fields' => array (
		array (
			'key' => 'field_56c59f66ec801',
			'label' => 'Layout Style',
			'name' => 'header_layout_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Single Image with Multiple CTA\'s',
				2 => 'Single Image with Single CTA',
				3 => 'Multiple Images with Single CTA',
				4 => 'Hero Style',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'allow_null' => 0,
		),
		array (
			'key' => 'field_56c5a43f4a6f2',
			'label' => 'Image',
			'name' => 'header_single_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '1',
					),
				),
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '2',
					),
				),
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '4',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 666,
			'min_height' => 498,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_4fvnd48fjvnrt',
			'label' => 'Mobile Image (optional)',
			'name' => 'header_single_image_mobile',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '4',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_58bd8aa7f0131',
			'label' => 'Image Position',
			'name' => 'header_image_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '1',
					),
				),
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '2',
					),
				),
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '4',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'top_left' => 'Top Left',
				'top_center' => 'Top Center',
				'top_right' => 'Top Right',
				'left_center' => 'Left Center',
				'center_center' => 'Center Center',
				'right_center' => 'Right Center',
				'bottom_left' => 'Bottom Left',
				'bottom_center' => 'Bottom Center',
				'bottom_right' => 'Bottom Right',
			),
			'default_value' => array (
				0 => 'center_center',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_58de3427a9991',
			'label' => 'Narrow Feature Image?',
			'name' => 'header_image_narrow',
			'type' => 'true_false',
			'instructions' => 'Checking this will reduce the overall height of the block.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '4',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56c5983271106',
			'label' => 'Image Left',
			'name' => 'header_image_third_left',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 454,
			'min_height' => 388,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56c5986371107',
			'label' => 'Image Middle',
			'name' => 'header_image_third_middle',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 454,
			'min_height' => 388,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56c5987b71108',
			'label' => 'Image Right',
			'name' => 'header_image_third_right',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 454,
			'min_height' => 388,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_58bd86ff60dac',
			'label' => 'Content Position',
			'name' => 'header_content_position',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '4',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'left' => 'Left',
				'center' => 'Center',
				'right' => 'Right',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Left',
			'layout' => 'vertical',
			'allow_null' => 0,
		),
		array (
			'key' => 'field_56c5989ba391e',
			'label' => 'Content Title',
			'name' => 'header_content_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c598b2a391f',
			'label' => 'Content Text',
			'name' => 'header_content_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58dc1713c883c',
			'label' => 'Text Style',
			'name' => 'header_content_text_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'light' => 'Light',
				'dark' => 'Dark',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_56c598f684d11',
			'label' => 'CTA Button Link Text',
			'name' => 'header_cta_button_single_link_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '2',
					),
				),
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '3',
					),
				),
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '4',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 15,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c598c0a3920',
			'label' => 'CTA Button Link Location',
			'name' => 'header_cta_button_single_link_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '2',
					),
				),
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '3',
					),
				),
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '4',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Internal URL',
				2 => 'External URL',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'allow_null' => 0,
		),
		array (
			'key' => 'field_56c5992684d12',
			'label' => 'CTA Button Link',
			'name' => 'header_cta_button_single_link_internal',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c598c0a3920',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '2',
					),
				),
				array (
					array (
						'field' => 'field_56c598c0a3920',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '3',
					),
				),
				array (
					array (
						'field' => 'field_56c598c0a3920',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '4',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_56c5993c84d13',
			'label' => 'CTA Button Link',
			'name' => 'header_cta_button_single_link_external',
			'type' => 'url',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c598c0a3920',
						'operator' => '==',
						'value' => '2',
					),
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '2',
					),
				),
				array (
					array (
						'field' => 'field_56c598c0a3920',
						'operator' => '==',
						'value' => '2',
					),
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '3',
					),
				),
				array (
					array (
						'field' => 'field_56c598c0a3920',
						'operator' => '==',
						'value' => '2',
					),
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '4',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_56c5a8d232f6e',
			'label' => 'CTA Buttons',
			'name' => 'header_multiple_cta_buttons',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c59f66ec801',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 3,
			'layout' => 'row',
			'button_label' => 'Add CTA',
			'sub_fields' => array (
				array (
					'key' => 'field_56c5a90232f6f',
					'label' => 'CTA Button Link Text',
					'name' => 'hedaer_cta_button_multiple_link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 15,
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c5a96d505bc',
					'label' => 'CTA Button Link Location',
					'name' => 'header_cta_button_multiple_link_location',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						1 => 'Internal URL',
						2 => 'External URL',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'allow_null' => 0,
				),
				array (
					'key' => 'field_56c5a999505bd',
					'label' => 'CTA Button Link',
					'name' => 'header_cta_button_multiple_link_internal',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56c5a96d505bc',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'ui' => 1,
				),
				array (
					'key' => 'field_56c5a9c2505be',
					'label' => 'CTA Button Link',
					'name' => 'header_cta_button_multiple_link_external',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56c5a96d505bc',
								'operator' => '==',
								'value' => '2',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/promotion-page.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
