<?php
// IMPORTANT - please don't overwrite this entire file with wordpress generated code
// instead, add each individual array one by one from the WP generated code
// as we have added some conditional logic

if( function_exists('acf_add_local_field_group') ):

$layouts = array();

$layouts['specific_news'] = array (
	'key' => '59511c15d0c71',
	'name' => 'specific_news',
	'label' => 'Specific News',
	'display' => 'row',
	'sub_fields' => array (
		array (
			'key' => 'field_59511c2ad0c72',
			'label' => 'Title',
			'name' => 'specific_news_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59511c3dd0c73',
			'label' => 'Text',
			'name' => 'specific_news_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_59511c56d0c74',
			'label' => 'News items',
			'name' => 'specific_news_items',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_59511c7ed0c75',
			'label' => 'Button text',
			'name' => 'specific_news_button_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59511ca4d0c76',
			'label' => 'Button link location',
			'name' => 'specific_news_button_link_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Internal URL',
				2 => 'External URL',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59511cd6d0c77',
			'label' => 'Button link',
			'name' => 'specific_news_button_link_internal',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59511ca4d0c76',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'allow_archives' => 1,
			'multiple' => 0,
		),
		array (
			'key' => 'field_59511d00d0c78',
			'label' => 'Button link',
			'name' => 'specific_news_button_link_external',
			'type' => 'url',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59511ca4d0c76',
						'operator' => '==',
						'value' => '2',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'min' => '',
	'max' => '',
);

$layouts['selected_pages'] = array (
	'key' => '5950ca32f4d0e',
	'name' => 'selected_pages',
	'label' => 'Selected Pages',
	'display' => 'row',
	'sub_fields' => array (
		array (
			'key' => 'field_5950ca3cf4d0f',
			'label' => 'Block title',
			'name' => 'selected_pages_block_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5950ca5cf4d10',
			'label' => 'Pages',
			'name' => 'selected_pages_pages',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 3,
			'max' => 3,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_5950cadaf4d12',
					'label' => 'Page',
					'name' => 'selected_pages_page',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'page',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
			),
		),
	),
	'min' => '',
	'max' => '',
);

$layouts['information'] = array (
	'key' => '594d24b3b7cd5',
	'name' => 'homepage_information_block',
	'label' => 'Information Block',
	'display' => 'row',
	'sub_fields' => array (
		array (
			'key' => 'field_594d24d0b7cd6',
			'label' => 'Title',
			'name' => 'homepage_information_block_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_594d25e4b7cd7',
			'label' => 'Text',
			'name' => 'homepage_information_block_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_594d2602b7cd8',
			'label' => 'Buttons',
			'name' => 'homepage_information_block_buttons',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_594d2620b7cd9',
					'label' => 'Button text',
					'name' => 'homepage_information_block_button_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_594d264db7cda',
					'label' => 'Button link location',
					'name' => 'homepage_information_block_button_link_location',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						1 => 'Internal URL',
						2 => 'External URL',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_594d2689b7cdb',
					'label' => 'Button link',
					'name' => 'homepage_information_block_button_link_internal',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_594d264db7cda',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array (
					'key' => 'field_594d2736b7cdc',
					'label' => 'Button link',
					'name' => 'homepage_information_block_button_link_external',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_594d264db7cda',
								'operator' => '==',
								'value' => '2',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'min' => '',
	'max' => '',
);

$layouts['cta'] = array (
	'key' => '56e15d5ca897d',
	'name' => 'homepage_cta_blocks',
	'label' => 'CTA Blocks',
	'display' => 'row',
	'sub_fields' => array (
		array (
			'key' => 'field_56e15dbaa897e',
			'label' => 'Block Title',
			'name' => 'homepage_cta_block_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56e15dd3a897f',
			'label' => 'CTA',
			'name' => 'homepage_cta_block',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 3,
			'max' => 3,
			'layout' => 'row',
			'button_label' => 'Add CTA',
			'sub_fields' => array (
				array (
					'key' => 'field_56e15defa8980',
					'label' => 'CTA Title',
					'name' => 'homepage_cta_block_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56e15e09a8981',
					'label' => 'CTA Image',
					'name' => 'homepage_cta_block_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => 545,
					'min_height' => 321,
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_56e15e3aa8982',
					'label' => 'CTA Link Text',
					'name' => 'homepage_cta_block_link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56e15e57a8983',
					'label' => 'CTA Link Location',
					'name' => 'homepage_cta_block_link_location',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						1 => 'Internal URL',
						2 => 'External URL',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'field_56e15e80a8984',
					'label' => 'CTA Link',
					'name' => 'homepage_cta_block_link_internal',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56e15e57a8983',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'ui' => 1,
				),
				array (
					'key' => 'field_56e15ea9a8985',
					'label' => 'CTA Link',
					'name' => 'homepage_cta_block_link_external',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56e15e57a8983',
								'operator' => '==',
								'value' => '2',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'min' => 0,
	'max' => 1,
);
$layouts['get_involved'] = array (
	'key' => '56e14d3ef27a7',
	'name' => 'homepage_get_involved_block',
	'label' => 'Get Involved Block',
	'display' => 'block',
	'sub_fields' => array (
		array (
			'key' => 'field_56e14d67f27a8',
			'label' => 'Block Title',
			'name' => 'homepage_gi_block_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56e14d87f27a9',
			'label' => 'CTA Block',
			'name' => 'homepage_gi_blocks',
			'type' => 'repeater',
			'instructions' => 'Fourth will only be displayed on mobile devices',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 4,
			'max' => 4,
			'layout' => 'row',
			'button_label' => 'Add CTA',
			'sub_fields' => array (
				array (
					'key' => 'field_56e14daef27aa',
					'label' => 'Post',
					'name' => 'post',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'services',
						1 => 'jobs',
						2 => 'post',
						3 => 'events',
						4 => 'page'
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'ui' => 1,
				),
			),
		),
	),
	'min' => 0,
	'max' => 1,
);
$layouts['campaign'] = array (
	'key' => '56e0559d0b976',
	'name' => 'homepage_campaign_block',
	'label' => 'Campaign Block',
	'display' => 'block',
	'sub_fields' => array (
		array (
			'key' => 'field_56e056a7ccb30',
			'label' => 'Title',
			'name' => 'hcb_title',
			'type' => 'text',
			'instructions' => 'The title of the homepage campaign block e.g \'Light up a life\'',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'E.g. \'Light up a life\'',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56e0570fccb31',
			'label' => 'Description',
			'name' => 'hcb_description',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'A description to go under the title.',
			'maxlength' => 150,
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56e05773ccb32',
			'label' => 'Link text',
			'name' => 'hcb_link_text',
			'type' => 'text',
			'instructions' => 'The title of the link that sits under the description.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Read more',
			'placeholder' => 'Enter a title for the link.',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56e057c2ccb33',
			'label' => 'Link Location',
			'name' => 'hcb_link_location',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Internal URL',
				2 => 'External URL',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56e05869ccb34',
			'label' => 'Link',
			'name' => 'hcb_link_internal_url',
			'type' => 'post_object',
			'instructions' => 'The url that the link should link to.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56e057c2ccb33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_56e058a1ccb35',
			'label' => 'Link',
			'name' => 'hcb_link_external_url',
			'type' => 'url',
			'instructions' => 'The url that the link should link to.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56e057c2ccb33',
						'operator' => '==',
						'value' => '2',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g. \'http://www.google.com\'',
		),
		array (
			'key' => 'field_56e058d4ccb36',
			'label' => 'Campaign video or image?',
			'name' => 'hcb_video_or_image',
			'type' => 'select',
			'instructions' => 'Choose whether you would like to add a video or an image to your campaign block.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Video' => 'Video',
				'Image' => 'Image',
			),
			'default_value' => array (
				'Video' => 'Video',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56e0593dccb37',
			'label' => 'Campaign video',
			'name' => 'hcb_video',
			'type' => 'oembed',
			'instructions' => 'Choose a video for the homepage campaign block.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56e058d4ccb36',
						'operator' => '==',
						'value' => 'Video',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
		array (
			'key' => 'field_56e0595eccb38',
			'label' => 'Campaign image',
			'name' => 'hcb_image',
			'type' => 'image',
			'instructions' => 'Choose an image for the homepage campaign block.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56e058d4ccb36',
						'operator' => '==',
						'value' => 'Image',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56e05993ccb39',
			'label' => 'Show Target',
			'name' => 'hcb_show_target',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56e059bbccb3a',
			'label' => 'Raised so far',
			'name' => 'hcb_raised_so_far',
			'type' => 'number',
			'instructions' => 'Enter the amount raised so far.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56e05993ccb39',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => 'Enter an amount with no commas or symbols.',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56e059faccb3b',
			'label' => 'Target',
			'name' => 'hcb_target',
			'type' => 'number',
			'instructions' => 'Enter the campaign target amount so far.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56e05993ccb39',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => 'Enter an amount with no commas or symbols.',
			'prepend' => '',
			'append' => '',
			'min' => -1,
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'min' => 0,
	'max' => 1,
);
// only show donation block fields if donations plugin installed
if( class_exists('CharityPressDonations\Plugin') ) {
	$layouts['donation'] = array (
		'key' => '56e1ae1976934',
		'name' => 'homepage_donation_block',
		'label' => 'Donation Block',
		'display' => 'row',
		'sub_fields' => array (
			array (
				'key' => 'field_56e1ae2e76935',
				'label' => 'Title',
				'name' => 'hdb_title',
				'type' => 'text',
				'instructions' => 'The title of the homepage campaign block e.g "Together we can do amazing things"',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Together we can do amazing things',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_56e1ae5676936',
				'label' => 'Description',
				'name' => 'hdb_description',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_56e1ae6d76937',
				'label' => 'Images',
				'name' => 'hdb_images',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 2,
				'max' => 2,
				'layout' => 'row',
				'button_label' => 'Add Row',
				'sub_fields' => array (
					array (
						'key' => 'field_56e1ae8f76938',
						'label' => 'Image',
						'name' => 'hdb_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
			array (
				'key' => 'field_56e1aeba76939',
				'label' => 'Buttons',
				'name' => 'hdb_buttons',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 1,
				'max' => 2,
				'layout' => 'row',
				'button_label' => 'Add Button',
				'sub_fields' => array (
					array (
						'key' => 'field_56e1aed47693a',
						'label' => 'Button Label',
						'name' => 'hdb_button_label',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_56e1aef47693b',
						'label' => 'Link Location',
						'name' => 'hdb_link_location',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							1 => 'Internal URL',
							2 => 'External URL',
						),
						'default_value' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
					),
					array (
						'key' => 'field_56e1af137693c',
						'label' => 'Link',
						'name' => 'hdb_link_internal_url',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_56e1aef47693b',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
						),
						'taxonomy' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
					array (
						'key' => 'field_56e1af357693d',
						'label' => 'Link',
						'name' => 'hdb_link_external_url',
						'type' => 'url',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_56e1aef47693b',
									'operator' => '==',
									'value' => '2',
								),
							),
						),
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
		),
		'min' => 0,
		'max' => 1,
	);
}
$layouts['latest_news'] = array (
	'key' => '56e1aa90e489a',
	'name' => 'homepage_latest_news',
	'label' => 'Latest News',
	'display' => 'row',
	'sub_fields' => array (
		array (
			'key' => 'field_56e1aab0e489b',
			'label' => 'Latest news title',
			'name' => 'latest_news_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'min' => 0,
	'max' => 1,
);
$layouts['wysiwyg_block'] = array (
	'key' => '580a233e85f35',
	'name' => 'homepage_wysiwyg_block',
	'label' => 'Wysiwyg Block',
	'display' => 'block',
	'sub_fields' => array (
		array (
			'key' => 'field_580a258aee168',
			'label' => 'Heading',
			'name' => 'homepage_wysiwyg_block_heading',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_580a25f0ee169',
			'label' => 'Row',
			'name' => 'homepage_wysiwyg_block_row',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_580a2648ee16a',
					'label' => 'Items',
					'name' => 'homepage_wysiwyg_block_items',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 2,
					'max' => 3,
					'layout' => 'block',
					'button_label' => 'Add Item',
					'sub_fields' => array (
						array (
							'key' => 'field_580a267bee16b',
							'label' => 'Item',
							'name' => 'homepage_wysiwyg_block_item',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_580a2715ee16c',
							'label' => 'Remove border?',
							'name' => 'homepage_wysiwyg_block_remove_border',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Check to remove the border for this item',
							'default_value' => 0,
						),
					),
				),
			),
		),
	),
	'min' => '',
	'max' => '',
);

$layouts['hero_banner'] = array (
	'key' => '58dcc14dfa0db',
	'name' => 'homepage_hero_banner',
	'label' => 'Hero Banner',
	'display' => 'block',
	'sub_fields' => array (
		array (
			'key' => 'field_58dcc352fa0dc',
			'label' => 'Image',
			'name' => 'homepage_hero_banner_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_58dcc392fa0dd',
			'label' => 'Mobile Image (optional)',
			'name' => 'homepage_hero_banner_mobile_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_58dcc591fa0de',
			'label' => 'Image Position',
			'name' => 'homepage_hero_banner_image_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'top_left' => 'Top Left',
				'top_center' => 'Top Center',
				'top_right' => 'Top Right',
				'left_center' => 'Left Center',
				'center_center' => 'Center Center',
				'right_center' => 'Right Center',
				'bottom_left' => 'Bottom Left',
				'bottom_center' => 'Bottom Center',
				'bottom_right' => 'Bottom Right',
			),
			'default_value' => array (
				0 => 'center_center',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_58dcc61dfa0df',
			'label' => 'Content Position',
			'name' => 'homepage_hero_banner_content_position',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'left' => 'Left',
				'center' => 'Center',
				'right' => 'Right',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'left',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_58dcc6aafa0e0',
			'label' => 'Content Title',
			'name' => 'homepage_hero_banner_content_title',
			'type' => 'text',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58dcc6b8fa0e1',
			'label' => 'Content Text',
			'name' => 'homepage_hero_banner_content_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 120,
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58dcc6ecfa0e2',
			'label' => 'Text Style',
			'name' => 'homepage_hero_banner_text_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'light' => 'Light',
				'dark' => 'Dark',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'light',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_58dcc74cfa0e3',
			'label' => 'CTA Button Link Text',
			'name' => 'homepage_hero_banner_cta_button_link_text',
			'type' => 'text',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58dcc7edfa0e4',
			'label' => 'CTA Button Link Location',
			'name' => 'homepage_hero_banner_cta_button_link_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Internal URL',
				2 => 'External URL',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_58dccd6dfa0e5',
			'label' => 'CTA Button Link',
			'name' => 'homepage_hero_banner_cta_button_link_internal',
			'type' => 'page_link',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58dcc7edfa0e4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_58dcce38fa0e6',
			'label' => 'CTA Button Link',
			'name' => 'homepage_hero_banner_cta_button_link_external',
			'type' => 'url',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58dcc7edfa0e4',
						'operator' => '==',
						'value' => '2',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'min' => '',
	'max' => '',
);

$layouts['promotion_block'] = array (
	'key' => '58dd3df56934e',
	'name' => 'homepage_promotion_block',
	'label' => 'Promotion Block',
	'display' => 'block',
	'sub_fields' => array (
		array (
			'key' => 'field_58dd407a6934f',
			'label' => 'Heading',
			'name' => 'homepage_promotion_block_heading',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58dd41e469350',
			'label' => 'Subheading',
			'name' => 'homepage_promotion_block_subheading',
			'type' => 'text',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58dd421369351',
			'label' => 'Text',
			'name' => 'homepage_promotion_block_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58dd4cdb7fd81',
			'label' => 'Text Style',
			'name' => 'homepage_promotion_block_text_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'light' => 'Light',
				'dark' => 'Dark',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'light',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_58dd432c69352',
			'label' => 'Image',
			'name' => 'homepage_promotion_block_image',
			'type' => 'image',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_58dd444269353',
			'label' => 'Background Image',
			'name' => 'homepage_promotion_block_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_58dd44fa69359',
			'label' => 'CTA Button Link Text',
			'name' => 'homepage_promotion_block_cta_button_link_text',
			'type' => 'text',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58dd450c6935a',
			'label' => 'CTA Button Link Location',
			'name' => 'homepage_promotion_block_cta_button_link_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Internal URL',
				2 => 'External URL',
			),
			'allow_null' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => '',
		),
		array (
			'key' => 'field_58dd452b6935b',
			'label' => 'CTA Button Link',
			'name' => 'homepage_promotion_block_cta_button_link_internal',
			'type' => 'page_link',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58dd450c6935a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'allow_null' => '',
			'multiple' => '',
		),
		array (
			'key' => 'field_58dd45566935c',
			'label' => 'CTA Button Link',
			'name' => 'homepage_promotion_block_cta_button_link_external',
			'type' => 'url',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58dd450c6935a',
						'operator' => '==',
						'value' => '2',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'min' => '',
	'max' => '',
);

$layouts['logo_carousel'] = array (
	'key' => '58e3b8378a349',
	'name' => 'homepage_logo_carousel',
	'label' => 'Logo Carousel',
	'display' => 'block',
	'sub_fields' => array (
		array (
			'key' => 'field_58e3b999b3169',
			'label' => 'Carousel Title',
			'name' => 'carousel_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58e3b84a8a34a',
			'label' => 'Logo Slide',
			'name' => 'logo_slide',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 7,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Logo Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_58e3b88c8a34b',
					'label' => 'Logo',
					'name' => 'logo',
					'type' => 'image',
					'instructions' => '<strong>Please note:</strong> If the logo height exceeds 200 pixels, the carousel layout may not work as expected.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'logo-carousel',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58e3b8ad8a34c',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58e3b8b68a34d',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => '',
				),
				array (
					'key' => 'field_58e3be6533397',
					'label' => 'Add an external link?',
					'name' => 'add_an_external_link',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_58e3b8ca8a34e',
					'label' => 'Link Text',
					'name' => 'link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58e3be6533397',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58e3b8e18a34f',
					'label' => 'Link URL',
					'name' => 'link_url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58e3be6533397',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'min' => '',
	'max' => '1',
);

acf_add_local_field_group(array (
	'key' => 'group_56e054e0190af',
	'title' => 'Homepage Flexible Content Blocks',
	'fields' => array (
		array (
			'key' => 'field_56e0551cccb2e',
			'label' => 'Homepage Flexible Content Blocks',
			'name' => 'homepage_flexible_content_blocks',
			'type' => 'flexible_content',
			'instructions' => 'These blocks can be added, removed and reordered.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Block',
			'min' => '',
			'max' => '',
			'layouts' => $layouts,
		),
	),
	'location' => array (
		array (
			array (
				'param'    => 'page_type',
				'operator' => '==',
				'value'    => 'front_page',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/promotion-page.php',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
