<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_56406b2aecdbc',
		'title'                 => 'Contact Page',
		'fields'                => array(
			array(
				'key'               => 'field_56445b4aa0751',
				'label'             => 'Main Content',
				'name'              => 'main_content',
				'type'              => 'flexible_content',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'button_label'      => 'Add Row',
				'min'               => '',
				'max'               => '',
				'layouts'           => array(
					array (
						'key' => 'fcf0d462b8d4e',
						'name' => 'content_wysiwyg_editor',
						'label' => 'WYSIWYG Editor',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_841a2d689ad86',
								'label' => 'Body',
								'name' => 'body',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
							),
							array (
								'key' => 'field_bd1611447453c',
								'label' => 'Add CTA Button?',
								'name' => 'add_cta_button',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_4ddc1899afa28',
								'label' => 'Button Text',
								'name' => 'button_text',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_bd1611447453c',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 'View more',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'readonly' => 0,
								'disabled' => 0,
							),
							array (
								'key' => 'field_5177fcd537152',
								'label' => 'Link Location',
								'name' => 'link_location',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_bd1611447453c',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'Internal Link' => 'Internal Link',
									'External Link' => 'External Link',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_c56c54b372cd0',
								'label' => 'Page Link',
								'name' => 'page_link',
								'type' => 'page_link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_bd1611447453c',
											'operator' => '==',
											'value' => '1',
										),
										array (
											'field' => 'field_5177fcd537152',
											'operator' => '==',
											'value' => 'Internal Link',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'post_type' => array (
								),
								'taxonomy' => array (
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_a4e36afe16bc9',
								'label' => 'External Link',
								'name' => 'external_link',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_bd1611447453c',
											'operator' => '==',
											'value' => '1',
										),
										array (
											'field' => 'field_5177fcd537152',
											'operator' => '==',
											'value' => 'External Link',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					array(
						'key'        => '56445b5d3f39f',
						'name'       => 'gravity_form',
						'label'      => 'Gravity Form',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_56445b72a0752',
								'label'             => 'Form',
								'name'              => 'form',
								'type'              => 'gravity_forms_field',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'allow_null'        => 0,
								'allow_multiple'    => 0,
							),
							array (
								'key' => 'field_5883534va13d',
								'label' => 'Show Form Title?',
								'name' => 'show_form_title_gravity_form',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_58543543cd',
								'label' => 'Show Form Description?',
								'name' => 'show_form_description_gravity_form',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
							),
						),
						'min'        => '',
						'max'        => '',
					),
				),
			),
			array(
				'key'               => 'field_564085ad81fd7',
				'label'             => 'Right Sidebar',
				'name'              => 'right_sidebar',
				'type'              => 'flexible_content',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'button_label'      => 'Add Row',
				'min'               => '',
				'max'               => '',
				'layouts'           => array(
					array(
						'key'        => '564084d71a4a6',
						'name'       => 'locations',
						'label'      => 'Locations',
						'display'    => 'table',
						'sub_fields' => array(
							array(
								'key'               => 'field_564085c881fd9',
								'label'             => 'Locations',
								'name'              => 'locations',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'collapsed'         => '',
								'min'               => '',
								'max'               => '',
								'layout'            => 'table',
								'button_label'      => 'Add Row',
								'sub_fields'        => array(
									array(
										'key'               => 'field_564085f881fda',
										'label'             => 'Name',
										'name'              => 'name',
										'type'              => 'text',
										'instructions'      => '',
										'required'          => 1,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'     => '',
										'placeholder'       => '',
										'prepend'           => '',
										'append'            => '',
										'maxlength'         => '',
										'readonly'          => 0,
										'disabled'          => 0,
									),
									array(
										'key'               => 'field_5640860e81fdb',
										'label'             => 'Address',
										'name'              => 'address',
										'type'              => 'textarea',
										'instructions'      => '',
										'required'          => 1,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'     => '',
										'placeholder'       => '',
										'maxlength'         => '',
										'rows'              => '',
										'new_lines'         => 'wpautop',
										'readonly'          => 0,
										'disabled'          => 0,
									),
									array(
										'key'               => 'field_5640861e81fdc',
										'label'             => 'Email',
										'name'              => 'email',
										'type'              => 'email',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'     => '',
										'placeholder'       => '',
										'prepend'           => '',
										'append'            => '',
									),
									array(
										'key'               => 'field_5640863781fdd',
										'label'             => 'Phone Number',
										'name'              => 'phone_number',
										'type'              => 'text',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'     => '',
										'placeholder'       => '',
										'prepend'           => '',
										'append'            => '',
										'maxlength'         => '',
										'readonly'          => 0,
										'disabled'          => 0,
									),
									array(
										'key'               => 'field_5640864181fde',
										'label'             => 'Fax Number',
										'name'              => 'fax_number',
										'type'              => 'text',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'     => '',
										'placeholder'       => '',
										'prepend'           => '',
										'append'            => '',
										'maxlength'         => '',
										'readonly'          => 0,
										'disabled'          => 0,
									),
								),
							),
						),
						'min'        => '',
						'max'        => '',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page_template',
					'operator' => '==',
					'value'    => 'templates/contact.php',
				),
			),
		),
		'menu_order'            => 1,
		'position'              => 'acf_after_title',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'the_content',
		),
		'active'                => 1,
		'description'           => '',
	) );

endif;
