<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_56b21bd847d1d',
		'title'                 => 'Services',
		'fields'                => array(
			array(
				'key'               => 'field_56c32c0c85fc8',
				'label'             => 'Show related',
				'name'              => 'show_related',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
			),
			array(
				'key'               => 'field_56c32c4085fc9',
				'label'             => 'Related title',
				'name'              => 'related_title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_56c32c0c85fc8',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_56c32c5885fca',
				'label'             => 'Related posts',
				'name'              => 'related_posts',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_56c32c0c85fc8',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => 2,
				'max'               => 2,
				'layout'            => 'block',
				'button_label'      => 'Add Post',
				'sub_fields'        => array(
					array(
						'key'               => 'field_56c32c7c85fcb',
						'label'             => 'Post',
						'name'              => 'post',
						'type'              => 'post_object',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'post_type'         => array(
							0 => 'services',
						),
						'taxonomy'          => array(),
						'allow_null'        => 0,
						'multiple'          => 0,
						'return_format'     => 'id',
						'ui'                => 1,
					),
				),
			),
			array(
				'key'               => 'field_56b228f44a22e',
				'label'             => 'Location',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_56b21bf05cead',
				'label'             => 'Location Name',
				'name'              => 'location_name',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_56b21c895ceae',
				'label'             => 'Location Address',
				'name'              => 'location_address',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => 'wpautop',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_56b21c955ceaf',
				'label'             => 'Map',
				'name'              => 'map',
				'type'              => 'google_map',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'center_lat'        => '',
				'center_lng'        => '',
				'zoom'              => '',
				'height'            => '',
			),
			array(
				'key'               => 'field_56b2295a4a22f',
				'label'             => 'General',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_56b22025bd80e',
				'label'             => 'Short Description',
				'name'              => 'short_description',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => 'wpautop',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_56b21cad5ceb4',
				'label'             => 'How to access title',
				'name'              => 'how_to_access_title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => 'wpautop',
				'readonly'          => 0,
				'disabled'          => 0,
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_56b21cad5ceb1',
				'label'             => 'How to access',
				'name'              => 'how_to_access',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => 'wpautop',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_56b2297d4a230',
				'label'             => 'Key Information',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_56b228d84a22c',
				'label'             => 'Instructor',
				'name'              => 'instructor',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_56b228e54a22d',
				'label'             => 'Cost',
				'name'              => 'cost',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_56b21e395ceb3',
				'label'             => 'Contact Details',
				'name'              => 'contact_details',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => 'field_56b21e485ceb4',
				'min'               => '',
				'max'               => '',
				'layout'            => 'row',
				'button_label'      => 'Add Contact Information',
				'sub_fields'        => array(
					array(
						'key'               => 'field_56b21e485ceb4',
						'label'             => 'Type',
						'name'              => 'type',
						'type'              => 'select',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(),
						'default_value'     => array(),
						'allow_null'        => 0,
						'multiple'          => 0,
						'ui'                => 0,
						'ajax'              => 0,
						'placeholder'       => '',
						'disabled'          => 0,
						'readonly'          => 0,
					),
					array(
						'key'               => 'field_56b21ebd5ceb6',
						'label'             => 'Email Address',
						'name'              => 'email_address',
						'type'              => 'email',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_56b21e485ceb4',
									'operator' => '==',
									'value'    => 'Email',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_56b21ed05ceb7',
						'label'             => 'Phone/Fax Number',
						'name'              => 'number',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_56b21e485ceb4',
									'operator' => '==',
									'value'    => 'Phone',
								),
							),
							array(
								array(
									'field'    => 'field_56b21e485ceb4',
									'operator' => '==',
									'value'    => 'Mobile',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
				),
			),
			array(
				'key'               => 'field_56b22ecb4a232',
				'label'             => 'Opening Times',
				'name'              => 'opening_times',
				'type'              => 'repeater',
				'instructions'      => 'Opening time for days that are not set will automatically be set to closed.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => 'field_56b22efc4a233',
				'min'               => '',
				'max'               => 7,
				'layout'            => 'table',
				'button_label'      => 'Add Day',
				'sub_fields'        => array(
					array(
						'key'               => 'field_56b22efc4a233',
						'label'             => 'Day of the week',
						'name'              => 'day_of_the_week',
						'type'              => 'select',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => 34,
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(),
						'default_value'     => array(),
						'allow_null'        => 0,
						'multiple'          => 0,
						'ui'                => 0,
						'ajax'              => 0,
						'placeholder'       => '',
						'disabled'          => 0,
						'readonly'          => 0,
					),
					array(
						'key'               => 'field_56b22f824a234',
						'label'             => 'Opening Time',
						'name'              => 'opening_time',
						'type'              => 'date_time_picker',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => 33,
							'class' => '',
							'id'    => '',
						),
						'show_date'         => 'false',
						'date_format'       => 'm/d/y',
						'time_format'       => 'h:mm tt',
						'show_week_number'  => 'false',
						'picker'            => 'slider',
						'save_as_timestamp' => 'true',
						'get_as_timestamp'  => 'false',
					),
					array(
						'key'               => 'field_56b22fbf4a235',
						'label'             => 'Closing Time',
						'name'              => 'closing_time',
						'type'              => 'date_time_picker',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => 33,
							'class' => '',
							'id'    => '',
						),
						'show_date'         => 'false',
						'date_format'       => 'm/d/y',
						'time_format'       => 'h:mm tt',
						'show_week_number'  => 'false',
						'picker'            => 'slider',
						'save_as_timestamp' => 'true',
						'get_as_timestamp'  => 'false',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'services',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'acf_after_title',
		'style'                 => 'default',
		'label_placement'       => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

endif;
